version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
      args:
        - work_dir=${WEB_WORK_DIR}
    volumes:
      - ./:/${WEB_WORK_DIR}
    ports:
      - "8000:8000"
    tty: true
  db:
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
